import ImageDefault from "../../public/images/data-not-found.png";
export const initData = {
  info: [
    {
      email: "",
      user_id: "",
      company_logo: "",
      estalishment: "",
      employers: "",
      needs_vn: "",
      needs_en: "",
      needs_jp: "",
      ceategory: "999",
      capital: "",
      address_vn: "",
      address_en: "",
      address_jp: "",
      languages: [],
      logo_associations: "",
      info_url: "",
      preview: ImageDefault,
    },
  ],
  description: {
    description: "",
    descriptionEN: "",
    descriptionJP: "",
  },
  products: [
    {
      id: Date.now(),
      product_name: "",
      product_name_EN: "",
      product_name_JP: "",
      product_description: "",
      product_description_EN: "",
      product_description_JP: "",
      product_picture: "",
      product_url: "",
      preview: ImageDefault,
    },
  ],
  specialities: [
    {
      id: 1,
      speciality_picture: "",
      speciality_desc: "",
      speciality_desc_en: "",
      speciality_desc_jp: "",
      preview: ImageDefault,
    },
    {
      id: 2,
      speciality_picture: "",
      speciality_desc: "",
      speciality_desc_en: "",
      speciality_desc_jp: "",
      preview: ImageDefault,
    },
    {
      id: 3,
      speciality_picture: "",
      speciality_desc: "",
      speciality_desc_en: "",
      speciality_desc_jp: "",
      preview: ImageDefault,
    },
  ],
  members: [
    {
      id: Date.now(),
      member_name: "",
      member_position: "",
      member_position_EN: "",
      member_position_JP: "",
      member_picture: "",
      member_desc: "",
      member_desc_JP: "",
      member_desc_EN: "",
      preview: ImageDefault,
    },
  ],
  clients: [
    {
      id: Date.now(),
      client_name: "",
      client_logo: "",
      client_url: "",
      client_url_EN: "",
      client_url_JP: "",
      preview: ImageDefault
    },
  ],
};
