export const pricingData = [
	{
	  key: 1,
	  service: 'Account register',
	  free: 'Self-register',
	  freeCheck: true,
	  lite: "Supported",
	  liteCheck: true,
	  standard: 'Supported',
	  standardCheck: true,
	  customize: "Được hỗ trợ",
	  isCustomize: 1,
	  premium: 'Supported',
	  premiumCheck: false
	},
	{
	  key: 2,
	  service: 'Account checking',
	  free: '~ 1 week',
	  freeCheck: true,
	  lite: "Within 24 hours",
	  liteCheck: true,
	  standard: 'Within 24 hours',
	  standardCheck: true,
	  customize: "Trong vòng 24h",
	  isCustomize: 1,
	  premium: 'Within 24 hours',
	  premiumCheck: false
	},
	{
	  key: 3,
	  service: 'Create company profiles 3 languages',
	  free: 'Self-created & updated',
	  freeCheck: true,
	  lite: "Supported",
	  liteCheck: true,
	  standard: 'Supported with Designer',
	  standardCheck: true,
	  customize: "Hỗ trợ designer",
	  isCustomize: 1,
	  premium: 'Supported with Designer',
	  premiumCheck: false
	},
	{
	  key: 4,
	  service: 'Evaluate company profile',
	  free: '~2 Weeks',
	  freeCheck: true,
	  lite: "~ 1 week",
	  liteCheck: true,
	  standard: '1-3 Days',
	  standardCheck: true,
	  customize: "1-3 ngày",
	  isCustomize: 1,
	  premium: '1-3 Days',
	  premiumCheck: false
	},
	{
	  key: 5,
	  service: 'Support translating contact content',
	  free: 'No',
	  freeCheck: false,
	  lite: "No",
	  liteCheck: false,
	  standard: '24/7',
	  standardCheck: true,
	  customize: "24/7",
	  isCustomize: 1,
	  premium: '24/7',
	  premiumCheck: false
	},
	{
	  key: 6,
	  service: 'Receive information when contacted',
	  free: 'Email',
	  freeCheck: true,
	  lite: "Email",
	  liteCheck: true,
	  standard: 'Email/Line(private) & Remind',
	  standardCheck: true,
	  customize: "Email/Zalo cá nhân & Remind",
	  isCustomize: 1,
	  premium: 'Email/Line(private) & Remind',
	  premiumCheck: false
	},
	{
	  key: 7,
	  service: 'Receive company information just registered',
	  free: 'Email',
	  freeCheck: true,
	  lite: "Email",
	  liteCheck: true,
	  standard: 'Email & Private Consultation',
	  standardCheck: true,
	  customize: "Email",
	  isCustomize: 1,
	  premium: 'Email & Private Consultation',
	  premiumCheck: false
	},
	{
	  key: 8,
	  service: 'Receive non-public opportunity information',
	  free: 'No',
	  freeCheck: false,
	  lite: "No",
	  liteCheck: false,
	  standard: 'Yes – Second priority',
	  standardCheck: true,
	  customize: "Có - Ưu tiên thứ 1",
	  isCustomize: 1,
	  premium: 'Yes – First priority',
	  premiumCheck: true
	},
	{
	  key: 9,
	  service: 'Commit to having at least 1 contact',
	  free: 'No',
	  freeCheck: false,
	  lite: "No",
	  liteCheck: false,
	  standard: 'No',
	  standardCheck: false,
	  customize: "Hoàn phí nếu không LH",
	  isCustomize: 2,
	  premium: "Fee refund if there isn't contact in 1 year",
	  premiumCheck: true
	},
	{
	  key: 10,
	  service: 'Support translation online meeting',
	  free: 'No',
	  freeCheck: false,
	  lite: "No",
	  liteCheck: false,
	  standard: 'No',
	  standardCheck: false,
	  customize: "Không",
	  isCustomize: 0,
	  premium: '1 time (up to 90 minutes)',
	  premiumCheck: true
	},
  ];